config/routes.rb
Rails.application.routes.draw do

  root 'dashboard#index'

  devise_for :users
  resources :users
  get 'profiles/register' => 'profiles#register'
  post 'profiles/create' => 'profiles#create'
  resources :trips
  resources :profiles
  resources :dashboard, only: [:index]
  resources :conversations, only: [:index, :show, :new, :create] do
    member do
      post :reply
      post :trash
      post :untrash
    end
  end

end

app/models/message.rb
class Message < ActiveRecord::Base
  belongs_to :user
end

app/models/profile.rb
class Profile < ActiveRecord::Base

  mount_uploader :avatar, AvatarUploader

  belongs_to :user
  validate :form_filled_out
  
  def form_filled_out
#    byebug
    if !avatar.present?
      errors.add(:avatar, "Upload an avatar, yo!")
    elsif !gender.present?
      errors.add(:gender, "What's yo gender!")
    elsif !seeking_gender.present?
      errors.add(:seeking_gender, "Who ya seeking?!")
    elsif !age.present?
      errors.add(:age, "What's yo age?!")
    elsif !about.present?
      errors.add(:about, "Give us some deets about you!")
    end
  end

end

app/models/trip.rb
class Trip < ActiveRecord::Base

  scope :destination, -> (destination) { where destination: destination }
  scope :gender, -> (gender) { 
    joins('LEFT JOIN users ON trips.user_id = users.id 
      LEFT JOIN profiles ON profiles.user_id = users.id').where('profiles.gender = ?', gender)
  }

  validates :destination, :start_date, :end_date, presence: true 
  belongs_to :user

  # has_many :profile, through: :user

  # def self.gender gender
  #   ids = Trip.all.map(&:user_id)
  #   profile_ids = Profile.where(gender: gender, user_id: ids).map(&:user_id)
  #   Trip.where(user_id: profile_ids)
  # end

  def destination_name
    country = ISO3166::Country[destination]
    country.translations[I18n.locale.to_s] || country.name
  end

  validate :form_filled_out

  def form_filled_out
#    byebug
    if !destination.present?
      errors.add(:destination, "Fill out a destination, yo!")
    elsif !start_date.present?
      errors.add(:start_date, "Fill in a start date!")
    elsif !end_date.present?
      errors.add(:end_date, "Fill in a end date!")
    end
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  #validates :eaten_goatleg, presence: true
  #validates :eaten_goatleg, presence: true
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  acts_as_messageable
  
  # You'd, probably, want to have a separate name column instead
  def name
    email
  end

  def mailboxer_email(object)
    email
  end
  has_one :profile
  has_many :trips
  has_many :messages
  accepts_nested_attributes_for :profile
  after_create :add_profile

  def add_profile
    Profile.create(user_id:self.id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  before_action :authenticate_user!, :except => [:index]
  protect_from_forgery with: :exception
end

app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController
  before_filter :authenticate_user!
  helper_method :mailbox, :conversation

  def create
    recipient_emails = conversation_params(:recipients).split(',')
    recipients = User.where(email: recipient_emails).all

    conversation = current_user.
      send_message(recipients, *conversation_params(:body, :subject)).conversation

    redirect_to conversation_path(conversation)
  end

  def reply
    current_user.reply_to_conversation(conversation, *message_params(:body, :subject))
    redirect_to conversation_path(conversation)
  end

  def trash
    conversation.move_to_trash(current_user)
    redirect_to :conversations
  end

  def untrash
    conversation.untrash(current_user)
    redirect_to :conversations
  end

  private

  def mailbox
    @mailbox ||= current_user.mailbox
  end

  def conversation
    @conversation ||= mailbox.conversations.find(params[:id])
  end

  def conversation_params(*keys)
    fetch_params(:conversation, *keys)
  end

  def message_params(*keys)
    fetch_params(:message, *keys)
  end

  def fetch_params(key, *subkeys)
    params[key].instance_eval do
      case subkeys.size
      when 0 then self
      when 1 then self[subkeys.first]
      else subkeys.map{|k| self[k] }
      end
    end
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :set_profile, only: [:edit, :update]



  def index
    @profiles = Profile.all
  end

  def show
    @profile = Profile.find(params[:id])
  end
  
  def new
    @profile = Profile.new
  end

  def create
    @profile = Profile.new(profile_params) 
    respond_to do |format|
      if @profile.save
        format.html { redirect_to @profile}
      else
        # format.html { render :register}
      end
    end
  end

  def update
    respond_to do |format|
      if @profile.update(profile_params)
        format.html { redirect_to @profile}
        format.json { render :show, status: :ok, location: @profile }
      else
        format.html { render :edit }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  def edit
  end

  private  
    def set_profile
        @profile = Profile.find(params[:id])
    end


private
  def profile_params
      params.require(:profile).permit(:user_id,:gender, :seeking_gender, :age, :username, :about, :avatar)
    end

end

app/controllers/trips_controller.rb
class TripsController < ApplicationController

  def index
    @profile = Profile.find(current_user.id)

    @trips = Trip.all
    @trips = @trips.destination(params[:destination]) if params[:destination].present?
    @trips = @trips.gender(params[:gender]) if params[:gender].present?

    @trips = @trips.sort_by &:end_date
  end

  def show
    @trip = Trip.find(params[:id])
  end

  def new
    @trip = Trip.new
  end

  def create
    @trip = Trip.new(trip_params)
    @trip.user_id = current_user.id

    respond_to do |format|
      if @trip.save
        format.html { redirect_to @trip, notice: 'Trip was successfully addded to yo itinerary!' }
        format.json { render :show, status: :created, location: @trip }
      else
        format.html { render :new }
        format.json { render json: @trip.errors, status: :unprocessable_entity }
      end
    end
  end

  private

  def set_trip
    @trip = Trip.find(params[:id])
  end

  def trip_params
    params.require(:trip).permit(:user_id, :destination, :start_date, :end_date)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/trips_helper.rb
module TripsHelper

  def gender g
    if g == "m"
      "male"
    else
      "female"
    end
  end

  def seeking_gender g
    if g == "m"
      "male"
    else
      "female"
    end
  end

end

app/views/conversations/_conversation.html.haml
= content_tag_for(:li, conversation) do |conversation|
  %p
    = link_to conversation.subject, conversation_path(conversation)
    |
    - if conversation.is_completely_trashed?(current_user)
      = link_to 'Untrash', untrash_conversation_path(conversation), method: :post
    - else
      = link_to 'Move to trash', trash_conversation_path(conversation), method: :post

app/views/conversations/_form.html.haml
= simple_form_for :conversation, url: :conversations do |f|
  = f.input :recipients
  = f.input :subject
  = f.input :body, as: :text
  .form-actions
    = f.button :submit, class: 'btn-primary'
    = f.button :submit, 'Cancel', type: :reset, class: 'btn-danger'

app/views/conversations/index.html.haml
%h1 Conversations
%h2 Inbox
%ul= render collection: mailbox.inbox, partial: 'conversation'
%h2 Sentbox
%ul= render collection: mailbox.sentbox, partial: 'conversation'
%h2 Trash
%ul= render collection: mailbox.trash, partial: 'conversation'

= link_to 'Start Conversation', :new_conversation

app/views/conversations/new.html.haml
%h1 Start Conversation
= render 'form'

app/views/conversations/show.html.haml
%h1= conversation.subject
%ul
  = content_tag_for(:li, conversation.receipts_for(current_user)) do |receipt|
    - message = receipt.message
    %h3= message.subject
    %p= message.body
= render 'messages/form', conversation: conversation

app/views/dashboard/index.html.erb
<% if !current_user %>

<div class="jumbotron">
  <h1>Goatleg</h1>
  <p class="lead">Because goats ain't got no arms...</p>
  <p>Finally, there's an app that allows the tightly-knit community of goat leg consumers to preserve their unique lifestyle with one another from anywhere in the world.</p>
  <p>And now it's just one click away.</p>
  <p><%= link_to "Sign up today, motherfucker!", new_user_registration_path, :class => "btn btn-lg btn-success", "role" => "button" %></p>
<br /><br /><br />
<div class="container">
  <div class="row">
    <div class="col-md-4">
      <img src="https://scontent-a-sjc.xx.fbcdn.net/hphotos-xfa1/v/t1.0-9/10922879_10204619982353834_560799776413417992_n.jpg?oh=e881f2f1998a61ffaccbfd65deeb3776&amp;oe=55580276" class="img-circle img-responsive" />
      <p class="text-center"><br />HAVE YOU</p>
    </div>
    <div class="col-md-4">
      <img src="http://wfas-maxcdn.woodstockfarmani.netdna-cdn.com/wp-content/uploads/2009/07/albienewleg.jpg" class="img-circle img-responsive" />
      <p class="text-center"><br />EATEN</p>
    </div>
    <div class="col-md-4">
      <img src="http://photos-h.ak.instagram.com/hphotos-ak-xaf1/t51.2885-15/10950528_1449447872012087_634144019_n.jpg" class="img-circle img-responsive" />
      <p class="text-center"><br />GOAT LEG?</p>
    </div>
  </div>
  <div class="row">&nbsp;</div>

</div>

<% else %>

<div class="container">
  <div class="row">
    <div class="col-md-4">
      <img src="http://i.huffpost.com/gadgets/slideshows/350430/slide_350430_3763099_free.jpg" class="img-responsive img-rounded" />
    </div>
    <div class="col-md-8">
      <h3>Dashboard</h3>
      <p>Welcome back, <%= current_user.email %>!</p>
    </div>
  </div>
</div>

<br /><br />

<div class="container text-center">
  <div class="row">
    <div class="btn-group" role="group" aria-label="...">
      <%= link_to "Account", new_user_registration_path, :class => "btn btn-lg btn-info", "role" => "button" %>
      <%= link_to "Update Profile", edit_profile_path(current_user.profile.id), :class => "btn btn-lg btn-info", "role" => "button" %>
      <%= link_to "Add New Trip", new_trip_path, :class => "btn btn-lg btn-info", "role" => "button" %>
    </div>
  </div>
  <div class="row">
    &nbsp;
  </div>
  <div class="row">
    <div class="btn-group" role="group" aria-label="...">
      <%= link_to "Trips", trips_path, :class => "btn btn-lg btn-default", "role" => "button" %>
      <%= link_to "Messages", conversations_path, :class => "btn btn-lg btn-default", "role" => "button" %>
    </div>
  </div>

  <div class="row">
    &nbsp;
  </div>
</div>

<!-- 
<div class="container">
  <div class="row">
    <div class="col-md-4">
      <img src="https://scontent-a-sjc.xx.fbcdn.net/hphotos-xfa1/v/t1.0-9/10922879_10204619982353834_560799776413417992_n.jpg?oh=e881f2f1998a61ffaccbfd65deeb3776&amp;oe=55580276" class="img-circle img-responsive" />
      <p class="text-center"><br />HAVE YOU</p>
    </div>
    <div class="col-md-4">
      <img src="http://wfas-maxcdn.woodstockfarmani.netdna-cdn.com/wp-content/uploads/2009/07/albienewleg.jpg" class="img-circle img-responsive" />
      <p class="text-center"><br />EATEN</p>
    </div>
    <div class="col-md-4">
      <img src="https://scontent-sjc.xx.fbcdn.net/hphotos-xaf1/v/t1.0-9/10177344_1540199399591821_2803772484236005738_n.jpg?oh=7ec032b42509914911475151909680c7&amp;oe=558F774A" class="img-circle img-responsive" />
      <p class="text-center"><br />GOAT LEG?</p>
    </div>
  </div>
  <div class="row">&nbsp;</div>
</div>
-->

<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Goatleg</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="container">

  <div class="header">

      <ul class="nav navbar-nav nav-pills navbar-right">
        <li><a href="/">Home</a></li>
        
        <% if current_user %>
        <li><%= link_to "View Trips", trips_path %></li>
        <li><%= link_to "<span class=\"glyphicon glyphicon-envelope\" aria-hidden=\"true\"></span>".html_safe, conversations_path %>
            <i class="inbox"><%= current_user.mailbox.inbox.count %></i></li>
        <% end %>

        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><%= current_user ? current_user.email : "Account" %> <span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <% if current_user %>

            <li><%= link_to "Dashboard", dashboard_index_path %></li>
            <li class="divider"></li>
            <li><%= link_to "Profile", profile_path(current_user.profile.id) %></li>
            <li><%= link_to "Edit Account", edit_user_registration_path %></li>
              <% if !Profile.find(current_user.profile.id) %>
                <li><%= link_to "Create Profile", new_profile_path %></li>
              <% else %>
                <li><%= link_to "Update Profile", edit_profile_path(current_user.profile.id) %></li>
              <% end %>
            <li class="divider"></li>
            <li><%= link_to "Add Trip", new_trip_path %></li>
            <li class="divider"></li>
            <li><%= link_to('Logout', destroy_user_session_path, :method => :delete) %></li>
            <% else %>
              <li><%= link_to "Register", new_user_registration_path %></li>
              <li><%= link_to "Sign In", new_user_session_path %></li>
            <% end %>
          </ul>
        </li>
      </ul>


    <h3 class="text-muted">Goatleg</h3>
  </div> <!-- .header -->





  <div class="container">
  <%= yield %>
  </div>
 
  <div class="footer">
    <p>Brought to you by:</p>
    <p>FAB-EZY, DENGUE DAN, POWDERED MILK, JENNERGY &amp; SPAGNO</p>
  </div>

</div> <!-- .container -->

</body>
</html>

app/views/messages/_form.html.haml
= simple_form_for :message, url: reply_conversation_path(conversation) do |f|
  = f.input :subject
  = f.input :body
  .form-actions
    = f.button :submit, class: 'btn-primary'
    = submit_tag 'Cancel', type: :reset, class: 'btn btn-danger'

app/views/profiles/_form.html.erb
<%= form_for @profile, html: { multipart: true, class: 'form-horizontal' }  do |f| %>
  
  <%= f.hidden_field :user_id, :value => @profile.user_id %>

  <% if @profile.errors.any? %>
    <div class="alert alert-danger">
      <ul>
        <% @profile.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= field_set_tag "Update/Edit Profile" do %>

  <div class="form_group">
    <%= f.label :username %>
    <br /><%= f.text_field :username %>
  </div>

  <div class="form_group">
    <%= f.label :gender %>
    <br /><%= select('profile', 'gender', %w[m f]) %>
  </div>

  <div class="form_group">
    <%= f.label :seeking_gender %>   
    <br /><%= select('profile', 'seeking_gender', %w[m f]) %>
  </div>

  <div class="form_group">
    <%= f.label :age %>
    <br /><%= f.number_field :age %>
  </div>

  <div class="form_group">
    <%= f.label :avatar %>
    <br /><%= f.file_field :avatar %>
  </div>
  <div class="form_group">
    <%= f.label :about %>
    <br /><%= f.text_area :about %>
  </div>

  <div class="form_group">
    <%= f.submit class: 'btn btn-primary' %>
  </div>

  <% end %>

<% end %>

app/views/profiles/edit.html.erb
<%= render 'form' %>
<%= link_to 'Back', profile_path %>

app/views/profiles/index.html.erb
profile listings

app/views/profiles/new.html.erb
<%= render 'form' %>
<%= link_to 'Back', profile_path %>

app/views/profiles/show.html.erb
<h2><%= @profile.username.blank? ? @profile.user.email : @profile.username%></h2>

<div class="container well well-lg">
  <div class="row">
    <div class="col-md-4">
      <% if @profile.avatar.blank? %>
      <%= image_tag(Gravatar.new(@profile.user.email).image_url, class: 'img-responsive img-circle')%>
      <% else %>
      <%= image_tag(@profile.avatar_url.to_s, class: 'img-responsive img-circle') %>
      <% end %>
    </div>
    <div class="col-md-8">
      <p>
        <%= gender(@profile.gender) %> seeking <%= gender(@profile.seeking_gender) %>
      </p>

      <p>
        <strong>Age:</strong> <%= @profile.age %>
      </p>

      <p>
        <strong>About:</strong> <%= simple_format(@profile.about) %>
      </p>
    </div>
  </div>
</div>

<% if @profile.user.trips.count > 0 %>
<h3>Trips</h3>
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
        <th>Destination</th>
        <th>From</th>
        <th>Until</th>
      </tr>
    </thead>
<% @profile.user.trips.each do |trip| %>
  <% if !trip.end_date.past? %>
      <tr>
        <td><%= trip.destination_name %></td>
        <td><%= trip.start_date.to_formatted_s(:long) %></td>
        <td><%= trip.end_date.to_formatted_s(:long) %></td>
      </tr>
  <% end %>
<% end %>
</table>
<% else %>
<h3>No upcoming Trips</h3>

<% if @profile.user_id == current_user.id %>
  <p><%= link_to "Add a new trip?", new_trip_path %></p>
<% end %>

<% end %>

app/views/trips/index.html.erb
<h2>Trips</h2> 
<table class="table table-striped table-bordered table-hover">
<thead>
  <tr>
    <th>E-mail</th>
    <th>Age</th>
    <th>Gender</th>
    <th>Seeking</th>
    <th>Destination</th>
    <th>Arrives</th>
    <th>Departs</th>
  </tr>
</thead>

<tbody>
<% @trips.each do |trip| %>
  <tr<%= trip.end_date.past? ? " class=\"active\"".html_safe : nil %>>
    <td><%= link_to(trip.user.profile.username, profile_path(trip.user.profile.id)) %></td>
    <td><%= trip.user.profile.age %></td>
    <td><%= link_to(trip.user.profile.gender, trips_path(:gender => trip.user.profile.gender)) %></td>
    <td><%= trip.user.profile.seeking_gender %></td>
    <td><%= link_to(trip.destination_name, trips_path(:destination => trip.destination)) %></td>
    <td><%= trip.start_date.to_formatted_s(:short) %></td>
    <td><%= trip.end_date.to_formatted_s(:long) %></td>
  </tr>

<% end %>
</tbody>

</table>

app/views/trips/new.html.erb
<%= form_for @trip, :html => { :class => 'form-horizontal'} do |f| %>

  <% if @trip.errors.any? %>
    <div class="alert alert-danger">
      <ul>
        <% @trip.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= field_set_tag "Add Trip" do %>

  <!-- 
  <% hidden_field(:trip, 'user_id', {value: current_user.id }) %>

  <div class="form-group">
    <%= f.label :user_id, class: 'control-label col-xs-2' %>
    <div class="col-xs-10">
      <%= select("trip", "user_id", User.all.collect { |u| [u.email, u.id] }, { selected: current_user.id }) %>
    </div>
  </div>
  -->


  <div class="form-group">
    <%= f.label :destination, class: 'control-label col-xs-2' %>
    <div class="col-xs-10">
      <%= country_select("trip", "destination") %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :start_date, class: 'control-label col-xs-2' %>
    <div class="col-xs-10">
      <%= date_field("trip", "start_date", { class: "form-control" } ) %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :end_date, class: 'control-label col-xs-2' %>
    <div class="col-xs-10">
      <%= date_field("trip", "end_date", { default: 2.weeks.from_now, class: "form-control" }) %>
    </div>
  </div>

  <div class="form-group">
    <div class="col-xs-offset-2 col-xs-10">
      <%= f.submit class: 'btn btn-primary' %>
    </div>
  </div>

  <% end %>

<% end %>

app/views/trips/show.html.erb
<div class="box">
  <h3><%= User.find(@trip.user.profile.id)[:email] %>, aged <%= Profile.find(@trip.user.profile.id)[:age] %></h3>

  <p><%= Profile.find(@trip.user.profile.id)[:gender] %> seeking <%= Profile.find(@trip.user.profile.id)[:seeking_gender] %></p>

  <p>
    Visiting <strong><%= @trip.destination_name %></strong> from <strong><%= @trip.start_date.to_formatted_s(:short) %></strong> to <strong><%= @trip.end_date.to_formatted_s(:short) %></strong>
  </p>
</div>

app/views/users/index.html.erb
<% @users.each do |user| %>
  <%= user.email %>
<% end %>

app/views/users/show.html.erb
THIS IS <%= @user.email %>